import XCTest
@testable import Hearth

/// A port of the Android ProvidersTest, which mirrors `frontend/src/import/providers.test.ts`,
/// `parseFile.test.ts` and `importFile.test.ts`: the same inputs, the same expected outputs.
final class ProvidersTests: XCTestCase {
    private let ancestry = [
        "#AncestryDNA raw data download",
        "#This file was generated by AncestryDNA at: 02/19/2021 10:00:00 UTC",
        "#Data was collected using AncestryDNA array version: V2.0",
        "#Genotype data reported here is on the forward (+) strand with respect to the human reference build 37.",
        "rsid\tchromosome\tposition\tallele1\tallele2",
        "rs3131972\t1\t752721\tA\tG",
    ].joined(separator: "\n")
    private let ttm = [
        "# This data file generated by 23andMe at: Sat Mar 17 06:10:10 2018",
        "# We are using reference human assembly build 37 (also known as Annotation Release 104).",
        "# rsid\tchromosome\tposition\tgenotype",
        "rs3131972\t1\t752721\tGA",
    ].joined(separator: "\n")
    private let mh = "##fileformat=MyHeritage\n##format=MHv1.0\n##reference=build37\nRSID,CHROMOSOME,POSITION,RESULT\n\"rs3131972\",\"1\",\"752721\",\"AG\""
    private let ftdna = "RSID,CHROMOSOME,POSITION,RESULT\nrs3131972,1,752721,AG"
    private let vcf = "##fileformat=VCFv4.2\n##source=Genotek\n##reference=hg19\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tmr3349\nchr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t0/1"
    private let ldna = "# Living DNA customer genotype data download file version: 1.0\n# rsid\tchromosome\tposition\tgenotype\nrs3131972\t1\t752721\tAG"

    private func call(_ a1: String, _ a2: String) -> Call {
        Call(rsid: "rs3131972", chromosome: "1", position: 752721, a1: a1, a2: a2)
    }

    private func parse(_ provider: Provider, _ line: String) -> Call? {
        GenomeParser.parser(provider)(Substring(line))
    }

    func testRecognisesEverySupportedHeader() {
        XCTAssertEqual(GenomeParser.detectProvider(ancestry), .ancestryDNA)
        XCTAssertEqual(GenomeParser.detectProvider(ttm), .twentyThreeAndMe)
        XCTAssertEqual(GenomeParser.detectProvider(mh), .myHeritage)
        XCTAssertEqual(GenomeParser.detectProvider(ftdna), .familyTreeDNA)
        XCTAssertEqual(GenomeParser.detectProvider(vcf), .genotekVCF)
        XCTAssertEqual(GenomeParser.detectProvider(ldna), .livingDNA)
        XCTAssertEqual(GenomeParser.detectProvider("rs1 1 100 AA\nrs2 1 200 CT"), .generic)
    }

    func testReadsTheBuild() {
        XCTAssertEqual(GenomeParser.detectBuild(ancestry), "37")
        XCTAssertEqual(GenomeParser.detectBuild(vcf), "37")
        XCTAssertEqual(GenomeParser.detectBuild("##reference=GRCh38"), "38")
    }

    func testAncestryDNA() {
        XCTAssertEqual(parse(.ancestryDNA, "rs3131972\t1\t752721\tA\tG"), call("A", "G"))
        XCTAssertNil(parse(.ancestryDNA, "rsid\tchromosome\tposition\tallele1\tallele2"))
        XCTAssertEqual(parse(.ancestryDNA, "rs1\t26\t100\tA\tA")?.chromosome, "MT")
        XCTAssertEqual(parse(.ancestryDNA, "rs1\t23\t100\tA\t0"), Call(rsid: "rs1", chromosome: "X", position: 100, a1: "A", a2: "-"))
    }

    func test23andMeAndLivingDNA() {
        XCTAssertEqual(parse(.twentyThreeAndMe, "rs3131972\t1\t752721\tGA"), call("G", "A"))
        XCTAssertEqual(
            parse(.twentyThreeAndMe, "rs548049170\t1\t69869\t--"),
            Call(rsid: "rs548049170", chromosome: "1", position: 69869, a1: "-", a2: "-")
        )
        XCTAssertEqual(parse(.livingDNA, "rs1\tX\t100\tA"), Call(rsid: "rs1", chromosome: "X", position: 100, a1: "A", a2: "-"))
    }

    func testMyHeritageAndFamilyTreeDNA() {
        XCTAssertEqual(parse(.myHeritage, "\"rs3131972\",\"1\",\"752721\",\"AG\""), call("A", "G"))
        XCTAssertNil(parse(.myHeritage, "RSID,CHROMOSOME,POSITION,RESULT"))
        XCTAssertEqual(parse(.familyTreeDNA, "rs3131972,1,752721,AG"), call("A", "G"))
    }

    func testGenotekVCFResolvesGTAgainstRefAndAlt() {
        XCTAssertEqual(parse(.genotekVCF, "chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t0/1"), call("A", "G"))
        XCTAssertEqual(parse(.genotekVCF, "chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t1/1"), call("G", "G"))
        XCTAssertEqual(parse(.genotekVCF, "chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t0/0"), call("A", "A"))
        XCTAssertEqual(
            parse(.genotekVCF, "chrM\t100\trs9\tA\tG\t.\t.\t.\tGT\t1"),
            Call(rsid: "rs9", chromosome: "MT", position: 100, a1: "G", a2: "-")
        )
        XCTAssertEqual(parse(.genotekVCF, "chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t./."), call("-", "-"))
        XCTAssertNil(parse(.genotekVCF, "#CHROM\tPOS"))
    }

    func testGenericAcceptsJoinedAndSplitGenotypesAndOddSeparators() {
        XCTAssertEqual(parse(.generic, "rs3131972 1 752721 AG"), call("A", "G"))
        XCTAssertEqual(parse(.generic, "rs3131972,1,752721,A,G"), call("A", "G"))
        XCTAssertEqual(parse(.generic, "rs3131972:1:752721:AG"), call("A", "G"))
    }

    func testHelpers() {
        XCTAssertEqual(GenomeParser.normaliseChromosome("chr1"), "1")
        XCTAssertEqual(GenomeParser.normaliseChromosome("chrM"), "MT")
        XCTAssertEqual(GenomeParser.normaliseChromosome("25"), "XY")
        let pair = { (g: String) -> [String] in
            let (a1, a2) = GenomeParser.splitGenotype(g)
            return [a1, a2]
        }
        XCTAssertEqual(pair("AG"), ["A", "G"])
        XCTAssertEqual(pair("--"), ["-", "-"])
        XCTAssertEqual(pair("DI"), ["D", "I"])
        XCTAssertEqual(pair(""), ["-", "-"])
    }

    func testCountsNoCallsAsSkipped() {
        let r = GenomeParser.parseRawText("# generated by 23andMe\nrs1\t1\t10\tAA\nrs2\t1\t20\t--\n")
        XCTAssertEqual(r.provider, .twentyThreeAndMe)
        XCTAssertEqual(r.calls.count, 1)
        XCTAssertEqual(r.skipped, 1)
    }

    /// Windows line ends: Swift reads "\r\n" as one Character, so the parser must split on bytes.
    func testReadsCRLFFiles() {
        let r = GenomeParser.parseRawText("# generated by 23andMe\r\nrs1\t1\t10\tAG\r\nrs2\t2\t20\tCT\r\n")
        XCTAssertEqual(r.calls, [
            Call(rsid: "rs1", chromosome: "1", position: 10, a1: "A", a2: "G"),
            Call(rsid: "rs2", chromosome: "2", position: 20, a1: "C", a2: "T"),
        ])
    }

    func testDerivesAPersonFromAFileName() {
        func person(_ name: String) -> [String] {
            let p = GenomeImport.personFromFileName(name)
            return [p.label, p.displayName]
        }
        XCTAssertEqual(person("AncestryDNA (1).txt"), ["ancestrydna-1", "AncestryDNA (1)"])
        XCTAssertEqual(person("alex_23andme.txt.zip"), ["alex-23andme", "alex_23andme"])
        XCTAssertEqual(person("genome_Maria.csv.gz"), ["genome-maria", "genome_Maria"])
        XCTAssertEqual(GenomeImport.personFromFileName(".txt").label, "genome")
    }

    func testUnpacksZipGzipAndPlainTextTheWayTheBrowserDoes() throws {
        let text = "\u{FEFF}" + ttm + "\n"
        let zip = storedZip([
            ("__MACOSX/._big.txt", Data(count: 10_000)),
            ("genome.txt", Data(text.utf8)),
            ("readme.txt", Data("hi".utf8)),
        ])
        let expected = { (inner: String) in GenomeImport.Unpacked(text: self.ttm + "\n", innerName: inner) }
        XCTAssertEqual(try GenomeImport.fileToText(zip, fileName: "export.zip"), expected("genome.txt"))
        XCTAssertEqual(try GenomeImport.fileToText(Gzip.compress(Data(text.utf8)), fileName: "g.txt.gz"), expected("g.txt"))
        XCTAssertEqual(try GenomeImport.fileToText(Data(text.utf8), fileName: "g.txt"), expected("g.txt"))
    }

    func testGzipRoundTrips() throws {
        let data = Data((0..<100_000).map { UInt8(truncatingIfNeeded: $0 % 251) })
        let gz = try Gzip.compress(data)
        XCTAssertEqual(Array(gz.prefix(2)), [0x1f, 0x8b])
        XCTAssertEqual(try Gzip.decompress(gz), data)
        XCTAssertThrowsError(try Gzip.decompress(gz.prefix(gz.count / 2)))
    }

    func testImportsAFileKeepsItsOriginalAndCleansUpAfterADelete() throws {
        let repo = try makeTestRepo()
        let p = try repo.addPerson(label: "alex", displayName: "Alex", sex: .female, birthYear: nil)
        let raw = ttm + "\nrs2\t2\t5\t--\n"
        let s = try GenomeImport.importFile(repo: repo, personId: p.id, data: Data(raw.utf8), fileName: "alex.txt")
        XCTAssertEqual(s, ImportSummary(calls: 1, provider: .twentyThreeAndMe, build: "37", skipped: 1))
        XCTAssertEqual(try repo.genotypeCounts(), [p.id: 1])
        XCTAssertEqual(repo.blobs.list(), [Repo.genomeBlobName(sha256Hex(raw))])
        XCTAssertThrowsError(
            try GenomeImport.importFile(repo: repo, personId: p.id, data: Data("nothing here".utf8), fileName: "x.txt")
        ) { error in
            XCTAssertTrue(error is NoCallsError)
        }
        try repo.deletePerson(id: p.id)
        XCTAssertEqual(try repo.genotypeCounts(), [:])
        XCTAssertEqual(repo.blobs.list(), [])
    }

    /// A zip of stored (uncompressed) entries, which is all `ZipReader` needs to be tested on: it
    /// does not check CRCs, so they are left zero.
    private func storedZip(_ entries: [(String, Data)]) -> Data {
        var out = Data()
        var directory = Data()
        func u16(_ v: Int, _ d: inout Data) { d.append(contentsOf: [UInt8(v & 0xff), UInt8(v >> 8 & 0xff)]) }
        func u32(_ v: Int, _ d: inout Data) { u16(v & 0xffff, &d); u16(v >> 16 & 0xffff, &d) }
        for (name, body) in entries {
            let offset = out.count
            let nameBytes = Data(name.utf8)
            u32(0x0403_4b50, &out)
            u16(20, &out); u16(0, &out); u16(0, &out); u16(0, &out); u16(0, &out)
            u32(0, &out); u32(body.count, &out); u32(body.count, &out)
            u16(nameBytes.count, &out); u16(0, &out)
            out.append(nameBytes)
            out.append(body)

            u32(0x0201_4b50, &directory)
            u16(20, &directory); u16(20, &directory); u16(0, &directory); u16(0, &directory)
            u16(0, &directory); u16(0, &directory)
            u32(0, &directory); u32(body.count, &directory); u32(body.count, &directory)
            u16(nameBytes.count, &directory); u16(0, &directory); u16(0, &directory)
            u16(0, &directory); u16(0, &directory); u32(0, &directory); u32(offset, &directory)
            directory.append(nameBytes)
        }
        let directoryStart = out.count
        out.append(directory)
        u32(0x0605_4b50, &out)
        u16(0, &out); u16(0, &out); u16(entries.count, &out); u16(entries.count, &out)
        u32(directory.count, &out); u32(directoryStart, &out); u16(0, &out)
        return out
    }
}
