import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { gzipSync, strToU8 } from 'fflate'
import { describe, expect, it } from 'vitest'
import { sha256Hex } from '../import/unpack'
import { type Container, genomePath, openContainer, serialiseContainer, sha256 } from './container'

/**
 * The golden backups the native apps test their restore against (ADR 0010): written by this code,
 * committed under mobile/fixtures/, and checked here so the web keeps opening them too. The data
 * is invented. `UPDATE_FIXTURES=1 npx vitest run src/export/fixtures.test.ts` rewrites them.
 */
const DIR = `${__dirname}/../../../mobile/fixtures`
const FIXTURE_PASSPHRASE = 'correct horse battery staple'

const journal: Container['journal'] = {
  persons: [
    {
      id: 'p-alex',
      label: 'alex',
      display_name: 'Alex',
      sex: 'female',
      birth_year: 1961,
      notes: '',
      created_at: '2026-01-02T10:00:00.000Z',
    },
    {
      id: 'p-sam',
      label: 'sam',
      display_name: 'Sam',
      sex: 'male',
      birth_year: 1990,
      notes: 'second child',
      created_at: '2026-01-02T10:05:00.000Z',
    },
  ],
  relationships: [{ parentId: 'p-alex', childId: 'p-sam' }],
  source_files: [],
  consents: [
    { kind: 'first_launch', version: 1, subject: '', grantedAt: '2026-01-02T09:59:00.000Z' },
    { kind: 'import_document', version: 1, subject: 'p-alex', grantedAt: '2026-01-03T08:00:00.000Z' },
  ],
  health_log: [
    {
      id: 'h-1',
      person_id: 'p-alex',
      date: '2026-09-14',
      time: '08:05',
      kind: 'measurement',
      title: 'Blood pressure',
      body: '',
      source: '',
      body_part: '',
      severity: null,
      tags: '',
      value: 128,
      value2: 84,
      unit: 'mmHg',
      created_at: '2026-09-14T06:05:00.000Z',
    },
    {
      id: 'h-2',
      person_id: 'p-alex',
      date: '2026-09-14',
      time: '',
      kind: 'symptom',
      title: 'Pain in both hands',
      body: 'Worse in the morning.\nEased by noon.',
      source: '',
      body_part: 'hands',
      severity: 6,
      tags: 'arthritis, flare',
      value: null,
      value2: null,
      unit: '',
      created_at: '2026-09-14T09:00:00.000Z',
    },
    {
      id: 'h-3',
      person_id: 'p-sam',
      date: '2026-08-30',
      time: '21:40',
      kind: 'measurement',
      title: 'Body temperature',
      body: '',
      source: '',
      body_part: '',
      severity: null,
      tags: '',
      value: 38.4,
      value2: null,
      unit: '°C',
      created_at: '2026-08-30T19:40:00.000Z',
    },
    {
      id: 'h-4',
      person_id: 'p-sam',
      date: '2026-07-01',
      kind: 'lab',
      title: 'Complete blood count',
      body: 'Hb 14.1 g/dL (13.5–17.5)',
      source: 'gemini-2.5-flash:2026-07-01',
      created_at: '2026-07-01T12:00:00.000Z',
    },
  ],
  attachments: [
    {
      id: 'a-1',
      health_log_id: 'h-4',
      person_id: 'p-sam',
      sha256: '0'.repeat(64),
      mime: 'application/pdf',
      bytes: 1234,
      name: 'cbc.pdf',
      created_at: '2026-07-01T12:00:00.000Z',
    },
  ],
  notes: [
    {
      id: 'n-1',
      person_id: 'p-alex',
      topic: 'rs429358',
      markdown: 'Ask at the next check-up.',
      updated_at: '2026-02-01T00:00:00.000Z',
    },
  ],
  chats: [],
  sharing_log: [
    { kind: 'ask', destination: 'gemini', payload: '{"n":1}', created_at: '2026-03-01T00:00:00.000Z' },
  ],
}

const container: Container = {
  header: {
    format: 'hearth-dump',
    version: 2,
    generation: 7,
    device: 'fixture-device',
    exported_at: '2026-09-21T00:00:00.000Z',
    encrypted: false,
  },
  manifest: { app_version: 'fixture', profile: 'default', genomes: [] },
  journal,
  genomes: {},
}

/**
 * Two invented 23andMe-format genomes at kb markers, for the genome restore and everything built on
 * it (findings, Mendelian checks, family lookups). Sam's rs4680 is AA against Alex's GG: one
 * Mendelian violation out of the autosomal calls they share. rs5 on X is left out of that count.
 */
const GENOMES: Record<string, string> = {
  'p-alex': `# This data file generated by 23andMe at: fixture
# We are using reference human assembly build 37
# rsid\tchromosome\tposition\tgenotype
rs429358\t19\t45411941\tTC
rs7412\t19\t45412079\tCC
rs1801133\t1\t11856378\tAG
rs4680\t22\t19951271\tGG
rs4149056\t12\t21331549\tTC
rs762551\t15\t75041917\tAA
rs5\tX\t100\tA
rs6\t1\t200\t--
`,
  'p-sam': `# This data file generated by 23andMe at: fixture
# We are using reference human assembly build 37
# rsid\tchromosome\tposition\tgenotype
rs429358\t19\t45411941\tTT
rs7412\t19\t45412079\tCT
rs1801133\t1\t11856378\tAA
rs4680\t22\t19951271\tAA
rs4149056\t12\t21331549\tCC
rs762551\t15\t75041917\tAC
rs5\tX\t100\tG
`,
}

/** The same family with both genomes inside: `genomes.hearth`. */
async function withGenomes(): Promise<Container> {
  const c: Container = {
    ...container,
    manifest: { ...container.manifest, genomes: [] },
    journal: { ...journal, source_files: [] },
    genomes: {},
  }
  for (const [personId, text] of Object.entries(GENOMES)) {
    const gz = gzipSync(strToU8(text), { mtime: 0 })
    const gzSha = await sha256(gz)
    const sf = {
      id: `sf-${personId}`,
      person_id: personId,
      provider: '23andme',
      build: '37',
      sha256: await sha256Hex(text),
      original_name: `${personId}.txt`,
      row_count: text.split('\n').filter((l) => /^rs\d+\t\S+\t\d+\t[A-Z]/.test(l)).length,
      imported_at: '2026-01-02T11:00:00.000Z',
    }
    c.journal.source_files.push(sf)
    c.manifest.genomes.push({
      path: genomePath(gzSha),
      sha256: gzSha,
      person_id: personId,
      source_file_id: sf.id,
      provider: '23andme',
      build: '37',
      kind: 'original',
    })
    c.genomes[genomePath(gzSha)] = gz
  }
  return c
}

describe('mobile fixtures', () => {
  if (process.env.UPDATE_FIXTURES) {
    it('writes them', async () => {
      if (!existsSync(DIR)) mkdirSync(DIR, { recursive: true })
      writeFileSync(`${DIR}/plain.hearth`, await serialiseContainer(container))
      writeFileSync(`${DIR}/encrypted.hearth`, await serialiseContainer(container, FIXTURE_PASSPHRASE))
      writeFileSync(`${DIR}/journal.json`, `${JSON.stringify(journal, null, 2)}\n`)
      writeFileSync(`${DIR}/genomes.hearth`, await serialiseContainer(await withGenomes()))
    })
    return
  }
  it('open to the committed journal, plain and encrypted', async () => {
    const expected = JSON.parse(readFileSync(`${DIR}/journal.json`, 'utf8'))
    expect(expected).toEqual(journal)
    const plain = await openContainer(new Uint8Array(readFileSync(`${DIR}/plain.hearth`)))
    expect(plain.journal).toEqual(journal)
    expect(plain.header.generation).toBe(7)
    const enc = await openContainer(
      new Uint8Array(readFileSync(`${DIR}/encrypted.hearth`)),
      FIXTURE_PASSPHRASE,
    )
    expect(enc.header.encrypted).toBe(true)
    expect(enc.journal).toEqual(journal)
  }, 20_000)
  // Backups the native apps wrote (their tests write them with UPDATE_FIXTURES=1): the web must
  // open each to the same family as the genome fixture it came from.
  for (const name of ['android.hearth', 'ios.hearth'])
    it(`opens ${name}, written by a native app`, async () => {
      if (!existsSync(`${DIR}/${name}`)) return
      const c = await openContainer(new Uint8Array(readFileSync(`${DIR}/${name}`)))
      const journal = (await withGenomes()).journal
      // A restore fills the columns an older row lacks (h-4), so a re-export carries them.
      const defaults = {
        time: '',
        source: '',
        body_part: '',
        severity: null,
        tags: '',
        value: null,
        value2: null,
        unit: '',
      }
      const want = {
        ...journal,
        health_log: journal.health_log.map((h) => ({ ...defaults, ...(h as object) })),
      }
      // Rows compare by content: key order is not part of the format (the JVM's org.json does not keep it).
      const canon = (r: unknown) => JSON.stringify(Object.fromEntries(Object.entries(r as object).sort()))
      const sorted = (rows: unknown[]) => rows.map(canon).sort()
      for (const table of ['persons', 'health_log', 'attachments', 'notes', 'source_files'] as const)
        expect(sorted(c.journal[table] ?? []), table).toEqual(sorted(want[table] ?? []))
      expect(c.journal.relationships).toEqual(want.relationships)
      expect(Object.keys(c.genomes)).toHaveLength(2)
    })

  it('open the genome fixture with both genomes intact', async () => {
    const c = await openContainer(new Uint8Array(readFileSync(`${DIR}/genomes.hearth`)))
    expect(c.journal).toEqual((await withGenomes()).journal)
    expect(Object.keys(c.genomes)).toHaveLength(2)
  })
})
