/**
 * Every consent the app can ask for (docs/design.md §13.1). The `version` bumps when the text
 * changes; a record for an older version does not count. Copy-out is confirmed per use and is
 * therefore not stored as a standing consent — it lands in the sharing log instead.
 */
export type ConsentKind =
  | 'first_launch'
  | 'import_genome'
  | 'import_minor'
  | 'import_document'
  | 'tier3_byok'
  | 'read_document_byok'
  | 'helper_backend'

export interface ConsentText {
  kind: ConsentKind
  version: number
  title: string
  statements: string[]
}

export const CONSENTS: Record<ConsentKind, ConsentText> = {
  first_launch: {
    kind: 'first_launch',
    version: 1,
    title: 'Before you start',
    statements: [
      'Everything I import stays in this browser. Hearth has no account and no server-side copy of my data; if I clear site data without exporting a dump, it is gone.',
      'Hearth is an informational tool, not a medical device. Nothing it shows is a diagnosis or treatment advice; I will talk to a qualified clinician before acting on it.',
      'Knowledge-base text may be wrong or outdated. Where it was generated by a language model it is labelled as such.',
      'I am at least 18 years old.',
    ],
  },
  import_genome: {
    kind: 'import_genome',
    version: 1,
    title: 'Importing a genome',
    statements: [
      'This DNA file is mine, or the person it belongs to has given me their explicit consent to store and analyse it here.',
      'I understand that a genome also reveals information about biological relatives who have not consented.',
      'Direct-to-consumer analysis of genetic data is legal where I live; I am responsible for checking that.',
    ],
  },
  import_minor: {
    kind: 'import_minor',
    version: 1,
    title: 'Adding a person under 18',
    statements: [
      "I am this child's parent or legal guardian.",
      'I have considered that the child may later wish this data had not been analysed, and I will delete it on their request.',
    ],
  },
  import_document: {
    kind: 'import_document',
    version: 1,
    title: 'Importing a medical document',
    statements: ['I am entitled to hold this document and to store it here for personal, household use.'],
  },
  tier3_byok: {
    kind: 'tier3_byok',
    version: 1,
    title: 'Sending questions with my own API key',
    statements: [
      "The previewed context pack will be sent directly from this browser to the provider I configure, under that provider's terms and privacy policy.",
      'My API key is stored only in this browser.',
      'I will still confirm every individual request before it is sent.',
    ],
  },
  read_document_byok: {
    kind: 'read_document_byok',
    version: 1,
    title: 'Reading documents with my own API key',
    statements: [
      "Each document I choose (the image or PDF itself) will be sent directly from this browser to the provider I configure, under that provider's terms and privacy policy.",
      'My API key is stored only in this browser. On a free-tier key the provider may use what I send to improve its models; a paid key is needed to prevent that.',
      'I will confirm every individual document before it is sent, and review the transcription before it is saved.',
    ],
  },
  helper_backend: {
    kind: 'helper_backend',
    version: 1,
    title: 'Using the Hearth helper service',
    statements: [
      'The previewed context pack will be processed in memory by the Hearth helper service in the EU and forwarded to the model provider. It is not stored, and no identifier links it to me.',
      'This is explicit consent under GDPR Article 9(2)(a) for that transient processing. I can withdraw it at any time by turning the feature off.',
    ],
  },
}
