import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { parseRawText } from './parseFile'

const SAMPLES = '/home/admin/DEV/personal/family_dna/samples'

function sample(name: string): string | null {
  try {
    return readFileSync(`${SAMPLES}/${name}`, 'utf8')
  } catch {
    return null
  }
}

describe('parseRawText on real exports (skipped when the private samples are absent)', () => {
  const cases: [string, string, number][] = [
    ['vova_AncestryDNA.txt', 'ancestrydna', 600000],
    ['bva_mr3349_23andme_V5.txt', '23andme', 500000],
    ['evb_myheritage.csv', 'myheritage', 500000],
    ['bva_genotek_m3349.vcf', 'genotek-vcf', 500000],
  ]
  for (const [file, provider, minCalls] of cases) {
    it(`${file} → ${provider}`, async () => {
      const text = sample(file)
      if (text === null) return
      const r = await parseRawText(text)
      expect(r.provider).toBe(provider)
      expect(r.calls.length).toBeGreaterThan(minCalls)
      const hit = r.calls.find((c) => c.rsid === 'rs3131972')
      expect(hit?.chromosome).toBe('1')
      expect(hit?.position).toBe(752721)
    })
  }
})

describe('parseRawText on inline text', () => {
  it('counts no-calls as skipped', async () => {
    const r = await parseRawText('# generated by 23andMe\nrs1\t1\t10\tAA\nrs2\t1\t20\t--\n')
    expect(r.provider).toBe('23andme')
    expect(r.calls).toHaveLength(1)
    expect(r.skipped).toBe(1)
  })
})
