import type { Call, Provider } from '../types'

/**
 * Provider detection and line parsing for consumer raw-data exports. Everything here is pure and
 * synchronous so it can be unit-tested against the real headers and run inside a worker.
 *
 * Formats (all build 37 unless a header says otherwise, all forward strand):
 *   AncestryDNA    tab: rsid chromosome position allele1 allele2   (chr 23=X 24=Y 25=XY 26=MT)
 *   23andMe        tab: rsid chromosome position genotype          (genotype "AG", "--")
 *   MyHeritage     csv, quoted: RSID,CHROMOSOME,POSITION,RESULT
 *   FamilyTreeDNA  csv: RSID,CHROMOSOME,POSITION,RESULT
 *   Living DNA     tab, 23andMe-like: rsid chromosome position genotype
 *   Genotek VCF    VCF 4.2 with a GT column; genotype resolved from REF/ALT
 *   generic        whitespace/comma/colon separated rsid chr pos genotype
 */

export function detectProvider(head: string): Provider {
  const h = head.slice(0, 4000)
  if (/##fileformat=VCF/i.test(h)) return 'genotek-vcf'
  if (/##fileformat=MyHeritage/i.test(h) || /MyHeritage DNA raw data/i.test(h)) return 'myheritage'
  if (/AncestryDNA/i.test(h) && /allele1\tallele2/i.test(h)) return 'ancestrydna'
  if (/generated by 23andMe/i.test(h)) return '23andme'
  if (/Living DNA/i.test(h)) return 'livingdna'
  if (/^RSID,CHROMOSOME,POSITION,RESULT/im.test(h)) return 'familytreedna'
  return 'generic'
}

export function detectBuild(head: string): string {
  const m = head.match(/build\s*(3[678])|GRCh(3[678])|hg(19|38)/i)
  if (!m) return '37'
  const v = m[1] ?? m[2] ?? m[3]
  if (v === '19') return '37'
  return v
}

const ANCESTRY_CHR: Record<string, string> = { '23': 'X', '24': 'Y', '25': 'XY', '26': 'MT' }

export function normaliseChromosome(raw: string): string {
  let c = raw.trim().replace(/^chr/i, '').toUpperCase()
  if (c === 'M' || c === 'MITO' || c === 'CHRM') c = 'MT'
  return ANCESTRY_CHR[c] ?? c
}

function normaliseAllele(a: string): string {
  const u = a.trim().toUpperCase()
  if (u === '' || u === '-' || u === '0' || u === '.' || u === 'N') return '-'
  return u
}

/** Splits a joined genotype like "AG", "A", "--", "DI" into two alleles. Haploid → (a, '-'). */
export function splitGenotype(g: string): [string, string] {
  const s = g
    .trim()
    .toUpperCase()
    .replace(/[^A-Z\-0]/g, '')
  if (s.length === 0) return ['-', '-']
  if (s.length === 1) return [normaliseAllele(s), '-']
  return [normaliseAllele(s[0]), normaliseAllele(s[1])]
}

export type LineParser = (line: string) => Call | null

function isHeaderOrEmpty(line: string): boolean {
  return line.length === 0 || line[0] === '#'
}

const parseAncestry: LineParser = (line) => {
  if (isHeaderOrEmpty(line) || line.startsWith('rsid')) return null
  const f = line.split('\t')
  if (f.length < 5) return null
  return {
    rsid: f[0],
    chromosome: normaliseChromosome(f[1]),
    position: Number(f[2]),
    a1: normaliseAllele(f[3]),
    a2: normaliseAllele(f[4]),
  }
}

const parse23andMe: LineParser = (line) => {
  if (isHeaderOrEmpty(line)) return null
  const f = line.split('\t')
  if (f.length < 4) return null
  const [a1, a2] = splitGenotype(f[3])
  return { rsid: f[0], chromosome: normaliseChromosome(f[1]), position: Number(f[2]), a1, a2 }
}

const parseCsvQuoted: LineParser = (line) => {
  if (isHeaderOrEmpty(line) || /^"?RSID/i.test(line)) return null
  const f = line.split(',').map((x) => x.replace(/^"|"$/g, '').trim())
  if (f.length < 4) return null
  const [a1, a2] = splitGenotype(f[3])
  return { rsid: f[0], chromosome: normaliseChromosome(f[1]), position: Number(f[2]), a1, a2 }
}

/** VCF with REF/ALT and a GT sample column. Genotype = GT indices resolved against REF/ALT. */
const parseVcf: LineParser = (line) => {
  if (isHeaderOrEmpty(line)) return null
  const f = line.split('\t')
  if (f.length < 10) return null
  const [chrom, pos, id, ref, alt, , , , format, sample] = f
  const gtIndex = format.split(':').indexOf('GT')
  if (gtIndex < 0) return null
  const gt = sample.split(':')[gtIndex]
  const alleles = [ref, ...alt.split(',')]
  const idx = gt.split(/[/|]/)
  const resolve = (i: string) => (i === '.' ? '-' : normaliseAllele(alleles[Number(i)] ?? '-'))
  const a1 = resolve(idx[0] ?? '.')
  const a2 = idx.length > 1 ? resolve(idx[1]) : '-'
  // Multi-base alleles (indels) are kept as-is; callers may filter on length.
  return {
    rsid: id === '.' ? `${normaliseChromosome(chrom)}:${pos}` : id,
    chromosome: normaliseChromosome(chrom),
    position: Number(pos),
    a1,
    a2,
  }
}

const parseGeneric: LineParser = (line) => {
  if (isHeaderOrEmpty(line) || /^rsid/i.test(line)) return null
  const f = line.split(/[\s,:;]+/).filter(Boolean)
  if (f.length < 4) return null
  if (f.length >= 5 && f[3].length === 1 && f[4].length === 1) {
    return {
      rsid: f[0],
      chromosome: normaliseChromosome(f[1]),
      position: Number(f[2]),
      a1: normaliseAllele(f[3]),
      a2: normaliseAllele(f[4]),
    }
  }
  const [a1, a2] = splitGenotype(f[3])
  return { rsid: f[0], chromosome: normaliseChromosome(f[1]), position: Number(f[2]), a1, a2 }
}

export const PARSERS: Record<Provider, LineParser> = {
  ancestrydna: parseAncestry,
  '23andme': parse23andMe,
  livingdna: parse23andMe,
  myheritage: parseCsvQuoted,
  familytreedna: parseCsvQuoted,
  'genotek-vcf': parseVcf,
  generic: parseGeneric,
}

export function isUsableCall(c: Call): boolean {
  return Number.isFinite(c.position) && c.position > 0 && c.rsid.length > 0 && !(c.a1 === '-' && c.a2 === '-')
}
