import { describe, expect, it } from 'vitest'
import { detectBuild, detectProvider, normaliseChromosome, PARSERS, splitGenotype } from './providers'

const ANCESTRY_HEAD = `#AncestryDNA raw data download
#This file was generated by AncestryDNA at: 02/19/2021 10:00:00 UTC
#Data was collected using AncestryDNA array version: V2.0
#Genotype data reported here is on the forward (+) strand with respect to the human reference build 37.
rsid\tchromosome\tposition\tallele1\tallele2
rs3131972\t1\t752721\tA\tG`

const TTM_HEAD = `# This data file generated by 23andMe at: Sat Mar 17 06:10:10 2018
# We are using reference human assembly build 37 (also known as Annotation Release 104).
# rsid\tchromosome\tposition\tgenotype
rs3131972\t1\t752721\tGA`

const MH_HEAD = `##fileformat=MyHeritage
##format=MHv1.0
##reference=build37
RSID,CHROMOSOME,POSITION,RESULT
"rs3131972","1","752721","AG"`

const FTDNA_HEAD = `RSID,CHROMOSOME,POSITION,RESULT
rs3131972,1,752721,AG`

const VCF_HEAD = `##fileformat=VCFv4.2
##source=Genotek
##reference=hg19
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tmr3349
chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t0/1`

const LDNA_HEAD = `# Living DNA customer genotype data download file version: 1.0
# rsid\tchromosome\tposition\tgenotype
rs3131972\t1\t752721\tAG`

describe('detectProvider', () => {
  it('recognises every supported header', () => {
    expect(detectProvider(ANCESTRY_HEAD)).toBe('ancestrydna')
    expect(detectProvider(TTM_HEAD)).toBe('23andme')
    expect(detectProvider(MH_HEAD)).toBe('myheritage')
    expect(detectProvider(FTDNA_HEAD)).toBe('familytreedna')
    expect(detectProvider(VCF_HEAD)).toBe('genotek-vcf')
    expect(detectProvider(LDNA_HEAD)).toBe('livingdna')
    expect(detectProvider('rs1 1 100 AA\nrs2 1 200 CT')).toBe('generic')
  })
  it('reads the build', () => {
    expect(detectBuild(ANCESTRY_HEAD)).toBe('37')
    expect(detectBuild(VCF_HEAD)).toBe('37')
    expect(detectBuild('##reference=GRCh38')).toBe('38')
  })
})

describe('parsers produce the same call for the same SNP across providers', () => {
  const expected = { rsid: 'rs3131972', chromosome: '1', position: 752721 }
  it('ancestrydna', () => {
    expect(PARSERS.ancestrydna('rs3131972\t1\t752721\tA\tG')).toEqual({ ...expected, a1: 'A', a2: 'G' })
    expect(PARSERS.ancestrydna('rsid\tchromosome\tposition\tallele1\tallele2')).toBeNull()
    expect(PARSERS.ancestrydna('rs1\t26\t100\tA\tA')?.chromosome).toBe('MT')
    expect(PARSERS.ancestrydna('rs1\t23\t100\tA\t0')).toEqual({
      rsid: 'rs1',
      chromosome: 'X',
      position: 100,
      a1: 'A',
      a2: '-',
    })
  })
  it('23andme / livingdna', () => {
    expect(PARSERS['23andme']('rs3131972\t1\t752721\tGA')).toEqual({ ...expected, a1: 'G', a2: 'A' })
    expect(PARSERS['23andme']('rs548049170\t1\t69869\t--')).toEqual({
      rsid: 'rs548049170',
      chromosome: '1',
      position: 69869,
      a1: '-',
      a2: '-',
    })
    expect(PARSERS.livingdna('rs1\tX\t100\tA')).toEqual({
      rsid: 'rs1',
      chromosome: 'X',
      position: 100,
      a1: 'A',
      a2: '-',
    })
  })
  it('myheritage / familytreedna', () => {
    expect(PARSERS.myheritage('"rs3131972","1","752721","AG"')).toEqual({ ...expected, a1: 'A', a2: 'G' })
    expect(PARSERS.myheritage('RSID,CHROMOSOME,POSITION,RESULT')).toBeNull()
    expect(PARSERS.familytreedna('rs3131972,1,752721,AG')).toEqual({ ...expected, a1: 'A', a2: 'G' })
  })
  it('genotek vcf resolves GT against REF/ALT', () => {
    const p = PARSERS['genotek-vcf']
    expect(p('chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t0/1')).toEqual({ ...expected, a1: 'A', a2: 'G' })
    expect(p('chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t1/1')).toEqual({ ...expected, a1: 'G', a2: 'G' })
    expect(p('chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t0/0')).toEqual({ ...expected, a1: 'A', a2: 'A' })
    expect(p('chrM\t100\trs9\tA\tG\t.\t.\t.\tGT\t1')).toEqual({
      rsid: 'rs9',
      chromosome: 'MT',
      position: 100,
      a1: 'G',
      a2: '-',
    })
    expect(p('chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t./.')).toEqual({ ...expected, a1: '-', a2: '-' })
    expect(p('#CHROM\tPOS')).toBeNull()
  })
  it('generic accepts both joined and split genotypes and odd separators', () => {
    expect(PARSERS.generic('rs3131972 1 752721 AG')).toEqual({ ...expected, a1: 'A', a2: 'G' })
    expect(PARSERS.generic('rs3131972,1,752721,A,G')).toEqual({ ...expected, a1: 'A', a2: 'G' })
    expect(PARSERS.generic('rs3131972:1:752721:AG')).toEqual({ ...expected, a1: 'A', a2: 'G' })
  })
})

describe('helpers', () => {
  it('normalises chromosomes', () => {
    expect(normaliseChromosome('chr1')).toBe('1')
    expect(normaliseChromosome('chrM')).toBe('MT')
    expect(normaliseChromosome('25')).toBe('XY')
  })
  it('splits genotypes', () => {
    expect(splitGenotype('AG')).toEqual(['A', 'G'])
    expect(splitGenotype('--')).toEqual(['-', '-'])
    expect(splitGenotype('DI')).toEqual(['D', 'I'])
    expect(splitGenotype('')).toEqual(['-', '-'])
  })
})
