package com.hearth.genome

import com.hearth.data.Call
import com.hearth.data.Provider

/**
 * Provider detection and line parsing for consumer raw-data exports: a port of
 * frontend/src/import/providers.ts, line for line, so a file reads to the same calls in every app.
 *
 * Formats (all build 37 unless a header says otherwise, all forward strand):
 *   AncestryDNA    tab: rsid chromosome position allele1 allele2   (chr 23=X 24=Y 25=XY 26=MT)
 *   23andMe        tab: rsid chromosome position genotype          (genotype "AG", "--")
 *   MyHeritage     csv, quoted: RSID,CHROMOSOME,POSITION,RESULT
 *   FamilyTreeDNA  csv: RSID,CHROMOSOME,POSITION,RESULT
 *   Living DNA     tab, 23andMe-like: rsid chromosome position genotype
 *   Genotek VCF    VCF 4.2 with a GT column; genotype resolved from REF/ALT
 *   generic        whitespace/comma/colon separated rsid chr pos genotype
 */

private val IC = setOf(RegexOption.IGNORE_CASE)

fun detectProvider(head: String): Provider {
    val h = head.take(4000)
    fun has(p: String) = Regex(p, IC).containsMatchIn(h)
    return when {
        has("##fileformat=VCF") -> Provider.GENOTEK_VCF
        has("##fileformat=MyHeritage") || has("MyHeritage DNA raw data") -> Provider.MYHERITAGE
        has("AncestryDNA") && has("allele1\tallele2") -> Provider.ANCESTRYDNA
        has("generated by 23andMe") -> Provider.TWENTYTHREEANDME
        has("Living DNA") -> Provider.LIVINGDNA
        Regex("^RSID,CHROMOSOME,POSITION,RESULT", setOf(RegexOption.IGNORE_CASE, RegexOption.MULTILINE)).containsMatchIn(h) -> Provider.FAMILYTREEDNA
        else -> Provider.GENERIC
    }
}

private val BUILD = Regex("""build\s*(3[678])|GRCh(3[678])|hg(19|38)""", IC)

fun detectBuild(head: String): String {
    val m = BUILD.find(head) ?: return "37"
    val v = m.groupValues.drop(1).first { it.isNotEmpty() }
    return if (v == "19") "37" else v
}

private val ANCESTRY_CHR = mapOf("23" to "X", "24" to "Y", "25" to "XY", "26" to "MT")

fun normaliseChromosome(raw: String): String {
    var c = raw.trim().replace(Regex("^chr", IC), "").uppercase()
    if (c == "M" || c == "MITO" || c == "CHRM") c = "MT"
    return ANCESTRY_CHR[c] ?: c
}

private fun normaliseAllele(a: String): String {
    val u = a.trim().uppercase()
    return if (u == "" || u == "-" || u == "0" || u == "." || u == "N") "-" else u
}

/** Splits a joined genotype like "AG", "A", "--", "DI" into two alleles. Haploid → (a, '-'). */
fun splitGenotype(g: String): Pair<String, String> {
    val s = g.trim().uppercase().replace(Regex("[^A-Z\\-0]"), "")
    return when (s.length) {
        0 -> "-" to "-"
        1 -> normaliseAllele(s) to "-"
        else -> normaliseAllele(s.substring(0, 1)) to normaliseAllele(s.substring(1, 2))
    }
}

typealias LineParser = (String) -> Call?

/** JS Number() on a position field: blanks and junk become 0, which isUsableCall then rejects. */
private fun position(s: String): Long = s.trim().let { if (it.isEmpty()) 0 else it.toLongOrNull() ?: -1 }

private fun isHeaderOrEmpty(line: String) = line.isEmpty() || line[0] == '#'

private val parseAncestry: LineParser = parse@{ line ->
    if (isHeaderOrEmpty(line) || line.startsWith("rsid")) return@parse null
    val f = line.split('\t')
    if (f.size < 5) return@parse null
    Call(f[0], normaliseChromosome(f[1]), position(f[2]), normaliseAllele(f[3]), normaliseAllele(f[4]))
}

private val parse23andMe: LineParser = parse@{ line ->
    if (isHeaderOrEmpty(line)) return@parse null
    val f = line.split('\t')
    if (f.size < 4) return@parse null
    val (a1, a2) = splitGenotype(f[3])
    Call(f[0], normaliseChromosome(f[1]), position(f[2]), a1, a2)
}

private val RSID_HEADER = Regex("^\"?RSID", IC)
private val QUOTES = Regex("^\"|\"$")

private val parseCsvQuoted: LineParser = parse@{ line ->
    if (isHeaderOrEmpty(line) || RSID_HEADER.containsMatchIn(line)) return@parse null
    val f = line.split(',').map { it.replace(QUOTES, "").trim() }
    if (f.size < 4) return@parse null
    val (a1, a2) = splitGenotype(f[3])
    Call(f[0], normaliseChromosome(f[1]), position(f[2]), a1, a2)
}

/** VCF with REF/ALT and a GT sample column. Genotype = GT indices resolved against REF/ALT. */
private val parseVcf: LineParser = parse@{ line ->
    if (isHeaderOrEmpty(line)) return@parse null
    val f = line.split('\t')
    if (f.size < 10) return@parse null
    val (chrom, pos, id, ref, alt) = f
    val gtIndex = f[8].split(':').indexOf("GT")
    if (gtIndex < 0) return@parse null
    val gt = f[9].split(':').getOrNull(gtIndex) ?: return@parse null
    val alleles = listOf(ref) + alt.split(',')
    val idx = gt.split(Regex("[/|]"))
    fun resolve(i: String) = if (i == ".") "-" else normaliseAllele(i.toIntOrNull()?.let { alleles.getOrNull(it) } ?: "-")
    val a1 = resolve(idx[0])
    val a2 = if (idx.size > 1) resolve(idx[1]) else "-"
    // Multi-base alleles (indels) are kept as-is; callers may filter on length.
    val chr = normaliseChromosome(chrom)
    Call(if (id == ".") "$chr:$pos" else id, chr, position(pos), a1, a2)
}

private val GENERIC_HEADER = Regex("^rsid", IC)
private val GENERIC_SEP = Regex("[\\s,:;]+")

private val parseGeneric: LineParser = parse@{ line ->
    if (isHeaderOrEmpty(line) || GENERIC_HEADER.containsMatchIn(line)) return@parse null
    val f = line.split(GENERIC_SEP).filter { it.isNotEmpty() }
    if (f.size < 4) return@parse null
    if (f.size >= 5 && f[3].length == 1 && f[4].length == 1)
        return@parse Call(f[0], normaliseChromosome(f[1]), position(f[2]), normaliseAllele(f[3]), normaliseAllele(f[4]))
    val (a1, a2) = splitGenotype(f[3])
    Call(f[0], normaliseChromosome(f[1]), position(f[2]), a1, a2)
}

val PARSERS: Map<Provider, LineParser> = mapOf(
    Provider.ANCESTRYDNA to parseAncestry,
    Provider.TWENTYTHREEANDME to parse23andMe,
    Provider.LIVINGDNA to parse23andMe,
    Provider.MYHERITAGE to parseCsvQuoted,
    Provider.FAMILYTREEDNA to parseCsvQuoted,
    Provider.GENOTEK_VCF to parseVcf,
    Provider.GENERIC to parseGeneric,
)

fun isUsableCall(c: Call): Boolean = c.position > 0 && c.rsid.isNotEmpty() && !(c.a1 == "-" && c.a2 == "-")

data class ParseResult(val provider: Provider, val build: String, val calls: List<Call>, val skipped: Int)

/** A whole raw-data text (parseFile.ts `parseRawText`). [onProgress] gets (characters done, total). */
fun parseRawText(text: String, forced: Provider? = null, onProgress: (Int, Int) -> Unit = { _, _ -> }): ParseResult {
    val provider = forced ?: detectProvider(text)
    val build = detectBuild(text)
    val parse = PARSERS.getValue(provider)
    val calls = ArrayList<Call>()
    var skipped = 0
    var start = 0
    var n = 0
    val total = text.length
    while (start < total) {
        var end = text.indexOf('\n', start)
        if (end < 0) end = total
        val line = text.substring(start, end).removeSuffix("\r")
        start = end + 1
        val c = parse(line) ?: continue
        if (isUsableCall(c)) calls.add(c) else skipped++
        if (++n % 50_000 == 0) onProgress(start, total)
    }
    onProgress(total, total)
    return ParseResult(provider, build, calls, skipped)
}
