package com.hearth.genome

import com.hearth.data.Blobs
import com.hearth.data.Call
import com.hearth.data.JdbcSql
import com.hearth.data.Provider
import com.hearth.data.Repo
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertThrows
import org.junit.Test
import java.io.ByteArrayOutputStream
import java.nio.file.Files
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/** Mirrors frontend/src/import/providers.test.ts, parseFile.test.ts and importFile.test.ts. */
class ProvidersTest {
    private val ancestry = """#AncestryDNA raw data download
#This file was generated by AncestryDNA at: 02/19/2021 10:00:00 UTC
#Data was collected using AncestryDNA array version: V2.0
#Genotype data reported here is on the forward (+) strand with respect to the human reference build 37.
rsid	chromosome	position	allele1	allele2
rs3131972	1	752721	A	G"""
    private val ttm = """# This data file generated by 23andMe at: Sat Mar 17 06:10:10 2018
# We are using reference human assembly build 37 (also known as Annotation Release 104).
# rsid	chromosome	position	genotype
rs3131972	1	752721	GA"""
    private val mh = "##fileformat=MyHeritage\n##format=MHv1.0\n##reference=build37\nRSID,CHROMOSOME,POSITION,RESULT\n\"rs3131972\",\"1\",\"752721\",\"AG\""
    private val ftdna = "RSID,CHROMOSOME,POSITION,RESULT\nrs3131972,1,752721,AG"
    private val vcf = "##fileformat=VCFv4.2\n##source=Genotek\n##reference=hg19\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tmr3349\nchr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t0/1"
    private val ldna = "# Living DNA customer genotype data download file version: 1.0\n# rsid\tchromosome\tposition\tgenotype\nrs3131972\t1\t752721\tAG"

    private fun call(a1: String, a2: String) = Call("rs3131972", "1", 752721, a1, a2)

    @Test fun `recognises every supported header`() {
        assertEquals(Provider.ANCESTRYDNA, detectProvider(ancestry))
        assertEquals(Provider.TWENTYTHREEANDME, detectProvider(ttm))
        assertEquals(Provider.MYHERITAGE, detectProvider(mh))
        assertEquals(Provider.FAMILYTREEDNA, detectProvider(ftdna))
        assertEquals(Provider.GENOTEK_VCF, detectProvider(vcf))
        assertEquals(Provider.LIVINGDNA, detectProvider(ldna))
        assertEquals(Provider.GENERIC, detectProvider("rs1 1 100 AA\nrs2 1 200 CT"))
    }

    @Test fun `reads the build`() {
        assertEquals("37", detectBuild(ancestry))
        assertEquals("37", detectBuild(vcf))
        assertEquals("38", detectBuild("##reference=GRCh38"))
    }

    @Test fun ancestrydna() {
        val p = PARSERS.getValue(Provider.ANCESTRYDNA)
        assertEquals(call("A", "G"), p("rs3131972\t1\t752721\tA\tG"))
        assertNull(p("rsid\tchromosome\tposition\tallele1\tallele2"))
        assertEquals("MT", p("rs1\t26\t100\tA\tA")?.chromosome)
        assertEquals(Call("rs1", "X", 100, "A", "-"), p("rs1\t23\t100\tA\t0"))
    }

    @Test fun `23andme and livingdna`() {
        assertEquals(call("G", "A"), PARSERS.getValue(Provider.TWENTYTHREEANDME)("rs3131972\t1\t752721\tGA"))
        assertEquals(Call("rs548049170", "1", 69869, "-", "-"), PARSERS.getValue(Provider.TWENTYTHREEANDME)("rs548049170\t1\t69869\t--"))
        assertEquals(Call("rs1", "X", 100, "A", "-"), PARSERS.getValue(Provider.LIVINGDNA)("rs1\tX\t100\tA"))
    }

    @Test fun `myheritage and familytreedna`() {
        assertEquals(call("A", "G"), PARSERS.getValue(Provider.MYHERITAGE)("\"rs3131972\",\"1\",\"752721\",\"AG\""))
        assertNull(PARSERS.getValue(Provider.MYHERITAGE)("RSID,CHROMOSOME,POSITION,RESULT"))
        assertEquals(call("A", "G"), PARSERS.getValue(Provider.FAMILYTREEDNA)("rs3131972,1,752721,AG"))
    }

    @Test fun `genotek vcf resolves GT against REF and ALT`() {
        val p = PARSERS.getValue(Provider.GENOTEK_VCF)
        assertEquals(call("A", "G"), p("chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t0/1"))
        assertEquals(call("G", "G"), p("chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t1/1"))
        assertEquals(call("A", "A"), p("chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t0/0"))
        assertEquals(Call("rs9", "MT", 100, "G", "-"), p("chrM\t100\trs9\tA\tG\t.\t.\t.\tGT\t1"))
        assertEquals(call("-", "-"), p("chr1\t752721\trs3131972\tA\tG\t.\t.\t.\tGT\t./."))
        assertNull(p("#CHROM\tPOS"))
    }

    @Test fun `generic accepts joined and split genotypes and odd separators`() {
        val p = PARSERS.getValue(Provider.GENERIC)
        assertEquals(call("A", "G"), p("rs3131972 1 752721 AG"))
        assertEquals(call("A", "G"), p("rs3131972,1,752721,A,G"))
        assertEquals(call("A", "G"), p("rs3131972:1:752721:AG"))
    }

    @Test fun helpers() {
        assertEquals("1", normaliseChromosome("chr1"))
        assertEquals("MT", normaliseChromosome("chrM"))
        assertEquals("XY", normaliseChromosome("25"))
        assertEquals("A" to "G", splitGenotype("AG"))
        assertEquals("-" to "-", splitGenotype("--"))
        assertEquals("D" to "I", splitGenotype("DI"))
        assertEquals("-" to "-", splitGenotype(""))
    }

    @Test fun `counts no-calls as skipped`() {
        val r = parseRawText("# generated by 23andMe\nrs1\t1\t10\tAA\nrs2\t1\t20\t--\n")
        assertEquals(Provider.TWENTYTHREEANDME, r.provider)
        assertEquals(1, r.calls.size)
        assertEquals(1, r.skipped)
    }

    @Test fun `derives a person from a file name`() {
        assertEquals("ancestrydna-1" to "AncestryDNA (1)", personFromFileName("AncestryDNA (1).txt"))
        assertEquals("alex-23andme" to "alex_23andme", personFromFileName("alex_23andme.txt.zip"))
        assertEquals("genome-maria" to "genome_Maria", personFromFileName("genome_Maria.csv.gz"))
        assertEquals("genome", personFromFileName(".txt").first)
    }

    @Test fun `unpacks zip, gzip and plain text the way the browser does`() {
        val text = "\uFEFF$ttm\n"
        val zip = ByteArrayOutputStream().also { out ->
            ZipOutputStream(out).use { z ->
                z.putNextEntry(ZipEntry("__MACOSX/._big.txt")); z.write(ByteArray(10_000)); z.closeEntry()
                z.putNextEntry(ZipEntry("genome.txt")); z.write(text.toByteArray()); z.closeEntry()
                z.putNextEntry(ZipEntry("readme.txt")); z.write("hi".toByteArray()); z.closeEntry()
            }
        }.toByteArray()
        assertEquals(Unpacked("$ttm\n", "genome.txt"), fileToText(zip, "export.zip"))
        assertEquals(Unpacked("$ttm\n", "g.txt"), fileToText(gzip(text.toByteArray()), "g.txt.gz"))
        assertEquals(Unpacked("$ttm\n", "g.txt"), fileToText(text.toByteArray(), "g.txt"))
    }

    @Test fun `imports a file, keeps its original, and a second import replaces the calls`() {
        val repo = Repo(JdbcSql(), Blobs(Files.createTempDirectory("blobs").toFile()))
        val p = repo.addPerson("alex", "Alex", com.hearth.data.Sex.FEMALE, null)
        val s = importGenomeFile(repo, p.id, "$ttm\nrs2\t2\t5\t--\n".toByteArray(), "alex.txt")
        assertEquals(ImportSummary(1, Provider.TWENTYTHREEANDME, "37", 1), s)
        assertEquals(mapOf(p.id to 1), repo.genotypeCounts())
        assertEquals(listOf(Repo.genomeBlobName(sha256Hex("$ttm\nrs2\t2\t5\t--\n"))), repo.blobs.list())
        assertThrows(NoCallsException::class.java) { importGenomeFile(repo, p.id, "nothing here".toByteArray(), "x.txt") }
        repo.deletePerson(p.id)
        assertEquals(emptyMap<String, Int>(), repo.genotypeCounts())
        assertEquals(emptyList<String>(), repo.blobs.list())
    }
}
