import Foundation

/// Provider detection and line parsing for consumer raw-data exports: a port of
/// `frontend/src/import/providers.ts` and `parseFile.ts`, line for line, so a file reads to the
/// same calls in every app.
///
/// Formats (all build 37 unless a header says otherwise, all forward strand):
///
///     AncestryDNA    tab: rsid chromosome position allele1 allele2   (chr 23=X 24=Y 25=XY 26=MT)
///     23andMe        tab: rsid chromosome position genotype          (genotype "AG", "--")
///     MyHeritage     csv, quoted: RSID,CHROMOSOME,POSITION,RESULT
///     FamilyTreeDNA  csv: RSID,CHROMOSOME,POSITION,RESULT
///     Living DNA     tab, 23andMe-like: rsid chromosome position genotype
///     Genotek VCF    VCF 4.2 with a GT column; genotype resolved from REF/ALT
///     generic        whitespace/comma/colon separated rsid chr pos genotype
///
/// A genome is 600 000 lines or more, so the line and field splitting works on UTF-8 bytes rather
/// than Characters: Swift treats "\r\n" as one Character, which a split on "\n" would never find,
/// and grapheme breaking is the slow path besides. Every split point is an ASCII byte, so each
/// piece is a valid Substring.
enum GenomeParser {
    typealias LineParser = (Substring) -> Call?

    struct ParseResult: Equatable {
        let provider: Provider
        let build: String
        let calls: [Call]
        let skipped: Int
    }

    // MARK: - Detection

    static func detectProvider(_ head: String) -> Provider {
        let h = String(head.prefix(4000)).lowercased()
        if h.contains("##fileformat=vcf") { return .genotekVCF }
        if h.contains("##fileformat=myheritage") || h.contains("myheritage dna raw data") { return .myHeritage }
        if h.contains("ancestrydna") && h.contains("allele1\tallele2") { return .ancestryDNA }
        if h.contains("generated by 23andme") { return .twentyThreeAndMe }
        if h.contains("living dna") { return .livingDNA }
        // `^` in the web's multiline regex: at the start or after any line break.
        let ftdna = "rsid,chromosome,position,result"
        if h.hasPrefix(ftdna) || h.contains("\n" + ftdna) || h.contains("\r" + ftdna) { return .familyTreeDNA }
        return .generic
    }

    private static let buildPattern = try! NSRegularExpression(
        pattern: #"build\s*(3[678])|GRCh(3[678])|hg(19|38)"#, options: [.caseInsensitive]
    )

    static func detectBuild(_ head: String) -> String {
        let ns = head as NSString
        guard let m = buildPattern.firstMatch(in: head, range: NSRange(location: 0, length: ns.length)) else {
            return "37"
        }
        for group in 1...3 {
            let r = m.range(at: group)
            if r.location != NSNotFound {
                let v = ns.substring(with: r)
                return v == "19" ? "37" : v
            }
        }
        return "37"
    }

    // MARK: - Helpers

    private static let ancestryChromosomes = ["23": "X", "24": "Y", "25": "XY", "26": "MT"]

    static func normaliseChromosome<S: StringProtocol>(_ raw: S) -> String {
        var c = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        if c.lowercased().hasPrefix("chr") { c = String(c.dropFirst(3)) }
        c = c.uppercased()
        if c == "M" || c == "MITO" || c == "CHRM" { c = "MT" }
        return ancestryChromosomes[c] ?? c
    }

    static func normaliseAllele<S: StringProtocol>(_ a: S) -> String {
        let u = a.trimmingCharacters(in: .whitespacesAndNewlines).uppercased()
        return ["", "-", "0", ".", "N"].contains(u) ? "-" : u
    }

    /// Splits a joined genotype like "AG", "A", "--", "DI" into two alleles. Haploid → (a, "-").
    static func splitGenotype<S: StringProtocol>(_ g: S) -> (String, String) {
        let kept = g.trimmingCharacters(in: .whitespacesAndNewlines).uppercased().unicodeScalars.filter { s in
            (s.value >= 0x41 && s.value <= 0x5a) || s == "-" || s == "0"
        }
        let s = String(String.UnicodeScalarView(kept))
        switch s.count {
        case 0: return ("-", "-")
        case 1: return (normaliseAllele(s), "-")
        default: return (normaliseAllele(s.prefix(1)), normaliseAllele(s.dropFirst().prefix(1)))
        }
    }

    /// JS `Number()` on a position field as the Kotlin port reads it: blank is 0, junk is -1, both
    /// of which `isUsableCall` rejects.
    private static func position(_ s: Substring) -> Int {
        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
        if t.isEmpty { return 0 }
        return Int(t) ?? -1
    }

    private static func isHeaderOrEmpty(_ line: Substring) -> Bool {
        line.isEmpty || line.utf8.first == UInt8(ascii: "#")
    }

    /// Whether `line` starts with `prefix`, ignoring ASCII case.
    private static func hasPrefixIgnoringCase(_ line: Substring, _ prefix: String) -> Bool {
        let p = Array(prefix.utf8)
        var i = line.utf8.startIndex
        for byte in p {
            guard i < line.utf8.endIndex else { return false }
            let b = line.utf8[i]
            let lower = (b >= 0x41 && b <= 0x5a) ? b + 32 : b
            if lower != byte { return false }
            i = line.utf8.index(after: i)
        }
        return true
    }

    /// Splits on one ASCII separator, keeping empty fields (Kotlin's `split(',')`, JS `split`).
    static func fields(_ line: Substring, _ separator: UInt8) -> [Substring] {
        var out: [Substring] = []
        var start = line.startIndex
        var i = line.utf8.startIndex
        while i < line.utf8.endIndex {
            if line.utf8[i] == separator {
                out.append(line[start..<i])
                start = line.utf8.index(after: i)
            }
            i = line.utf8.index(after: i)
        }
        out.append(line[start..<line.endIndex])
        return out
    }

    /// Splits on runs of any of `separators`, dropping empty fields (the generic format's
    /// `split(/[\s,:;]+/).filter(Boolean)`).
    private static func tokens(_ line: Substring, _ separators: Set<UInt8>) -> [Substring] {
        var out: [Substring] = []
        var start: Substring.Index?
        var i = line.utf8.startIndex
        while i < line.utf8.endIndex {
            if separators.contains(line.utf8[i]) {
                if let s = start { out.append(line[s..<i]) }
                start = nil
            } else if start == nil {
                start = i
            }
            i = line.utf8.index(after: i)
        }
        if let s = start { out.append(line[s..<line.endIndex]) }
        return out
    }

    /// Java's `\s` (space, tab, newline, vertical tab, form feed, carriage return) and `,:;`.
    private static let genericSeparators: Set<UInt8> = [0x20, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x2c, 0x3a, 0x3b]

    // MARK: - Line parsers

    private static func parseAncestry(_ line: Substring) -> Call? {
        if isHeaderOrEmpty(line) || line.hasPrefix("rsid") { return nil }
        let f = fields(line, 0x09)
        if f.count < 5 { return nil }
        return Call(
            rsid: String(f[0]), chromosome: normaliseChromosome(f[1]), position: position(f[2]),
            a1: normaliseAllele(f[3]), a2: normaliseAllele(f[4])
        )
    }

    private static func parse23andMe(_ line: Substring) -> Call? {
        if isHeaderOrEmpty(line) { return nil }
        let f = fields(line, 0x09)
        if f.count < 4 { return nil }
        let (a1, a2) = splitGenotype(f[3])
        return Call(rsid: String(f[0]), chromosome: normaliseChromosome(f[1]), position: position(f[2]), a1: a1, a2: a2)
    }

    private static func parseCsvQuoted(_ line: Substring) -> Call? {
        if isHeaderOrEmpty(line) { return nil }
        if hasPrefixIgnoringCase(line, "rsid") || hasPrefixIgnoringCase(line, "\"rsid") { return nil }
        let f = fields(line, 0x2c).map { field -> Substring in
            var v = field
            if v.hasPrefix("\"") { v = v.dropFirst() }
            if v.hasSuffix("\"") { v = v.dropLast() }
            return Substring(v.trimmingCharacters(in: .whitespacesAndNewlines))
        }
        if f.count < 4 { return nil }
        let (a1, a2) = splitGenotype(f[3])
        return Call(rsid: String(f[0]), chromosome: normaliseChromosome(f[1]), position: position(f[2]), a1: a1, a2: a2)
    }

    /// VCF with REF/ALT and a GT sample column. Genotype = GT indices resolved against REF/ALT.
    private static func parseVcf(_ line: Substring) -> Call? {
        if isHeaderOrEmpty(line) { return nil }
        let f = fields(line, 0x09)
        if f.count < 10 { return nil }
        let chrom = f[0], pos = f[1], id = f[2], ref = f[3], alt = f[4]
        guard let gtIndex = fields(f[8], 0x3a).firstIndex(of: "GT") else { return nil }
        let sample = fields(f[9], 0x3a)
        guard gtIndex < sample.count else { return nil }
        let gt = sample[gtIndex]
        let alleles = [ref] + fields(alt, 0x2c)
        let idx = gt.split(omittingEmptySubsequences: false) { $0 == "/" || $0 == "|" }
        func resolve(_ i: Substring) -> String {
            if i == "." { return "-" }
            guard let n = Int(i), n >= 0, n < alleles.count else { return "-" }
            return normaliseAllele(alleles[n])
        }
        let a1 = resolve(idx[0])
        let a2 = idx.count > 1 ? resolve(idx[1]) : "-"
        // Multi-base alleles (indels) are kept as they are; callers may filter on length.
        let chr = normaliseChromosome(chrom)
        return Call(rsid: id == "." ? "\(chr):\(pos)" : String(id), chromosome: chr, position: position(pos), a1: a1, a2: a2)
    }

    private static func parseGeneric(_ line: Substring) -> Call? {
        if isHeaderOrEmpty(line) || hasPrefixIgnoringCase(line, "rsid") { return nil }
        let f = tokens(line, genericSeparators)
        if f.count < 4 { return nil }
        if f.count >= 5 && f[3].count == 1 && f[4].count == 1 {
            return Call(
                rsid: String(f[0]), chromosome: normaliseChromosome(f[1]), position: position(f[2]),
                a1: normaliseAllele(f[3]), a2: normaliseAllele(f[4])
            )
        }
        let (a1, a2) = splitGenotype(f[3])
        return Call(rsid: String(f[0]), chromosome: normaliseChromosome(f[1]), position: position(f[2]), a1: a1, a2: a2)
    }

    /// `PARSERS`.
    static func parser(_ provider: Provider) -> LineParser {
        switch provider {
        case .ancestryDNA: return parseAncestry
        case .twentyThreeAndMe, .livingDNA: return parse23andMe
        case .myHeritage, .familyTreeDNA: return parseCsvQuoted
        case .genotekVCF: return parseVcf
        case .generic: return parseGeneric
        }
    }

    static func isUsableCall(_ c: Call) -> Bool {
        c.position > 0 && !c.rsid.isEmpty && !(c.a1 == "-" && c.a2 == "-")
    }

    // MARK: - Whole files

    /// A whole raw-data text (`parseRawText`). `onProgress` gets (bytes done, total) every 50 000
    /// lines and once at the end, on the calling thread.
    static func parseRawText(
        _ text: String, forced: Provider? = nil, onProgress: ((Int, Int) -> Void)? = nil
    ) -> ParseResult {
        let provider = forced ?? detectProvider(text)
        let build = detectBuild(text)
        let parse = parser(provider)
        var calls: [Call] = []
        var skipped = 0
        var n = 0
        let utf8 = text.utf8
        let total = utf8.count
        var done = 0
        var start = utf8.startIndex
        while start < utf8.endIndex {
            let end = utf8[start...].firstIndex(of: UInt8(ascii: "\n")) ?? utf8.endIndex
            var line = text[start..<end]
            done += utf8.distance(from: start, to: end) + 1
            start = end < utf8.endIndex ? utf8.index(after: end) : end
            if line.utf8.last == UInt8(ascii: "\r") {
                line = line[line.startIndex..<line.utf8.index(before: line.endIndex)]
            }
            guard let c = parse(line) else { continue }
            if isUsableCall(c) { calls.append(c) } else { skipped += 1 }
            n += 1
            if n % 50_000 == 0 { onProgress?(min(done, total), total) }
        }
        onProgress?(total, total)
        return ParseResult(provider: provider, build: build, calls: calls, skipped: skipped)
    }
}
